title: Carmelo R. Milano N. # your name (or website title) here
logo: "/images/bio-photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst / Systems Engineering Student
  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
