title: Carmelo Milano # your name (or website title) here
logo: "/images/bio-photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align='center'> <a href="/pdf/CV-CarmeloMilano.pdf">Resume</a> | <a href="https://www.linkedin.com/in/carmelo-milano/">LinkedIn</a> </p>
  
  Data Analyst / Systems Engineering Student
  <br>
  Pursuing a career in data science, as a data analyst. 
  Seeking for new challenges that allow me to continue learning and apply the skills I have acquired. 
  <br><br>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
